package vu.lt.mybatis.model;

public class Artist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ARTIST.ID
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ARTIST.AGE
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ARTIST.FIRST_NAME
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ARTIST.LAST_NAME
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ARTIST.STAGE_NAME
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    private String stageName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ARTIST.ID
     *
     * @return the value of PUBLIC.ARTIST.ID
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ARTIST.ID
     *
     * @param id the value for PUBLIC.ARTIST.ID
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ARTIST.AGE
     *
     * @return the value of PUBLIC.ARTIST.AGE
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ARTIST.AGE
     *
     * @param age the value for PUBLIC.ARTIST.AGE
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ARTIST.FIRST_NAME
     *
     * @return the value of PUBLIC.ARTIST.FIRST_NAME
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ARTIST.FIRST_NAME
     *
     * @param firstName the value for PUBLIC.ARTIST.FIRST_NAME
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ARTIST.LAST_NAME
     *
     * @return the value of PUBLIC.ARTIST.LAST_NAME
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ARTIST.LAST_NAME
     *
     * @param lastName the value for PUBLIC.ARTIST.LAST_NAME
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ARTIST.STAGE_NAME
     *
     * @return the value of PUBLIC.ARTIST.STAGE_NAME
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    public String getStageName() {
        return stageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ARTIST.STAGE_NAME
     *
     * @param stageName the value for PUBLIC.ARTIST.STAGE_NAME
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    public void setStageName(String stageName) {
        this.stageName = stageName;
    }
}