package vu.lt.mybatis.model;

public class Label {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LABEL.ID
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LABEL.NAME
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LABEL.ID
     *
     * @return the value of PUBLIC.LABEL.ID
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LABEL.ID
     *
     * @param id the value for PUBLIC.LABEL.ID
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LABEL.NAME
     *
     * @return the value of PUBLIC.LABEL.NAME
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LABEL.NAME
     *
     * @param name the value for PUBLIC.LABEL.NAME
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}