package vu.lt.mybatis.model;

public class Song {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.ID
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.NAME
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.TEMPO
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    private Integer tempo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.ARTIST_ID
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    private Integer artistId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.ID
     *
     * @return the value of PUBLIC.SONG.ID
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.ID
     *
     * @param id the value for PUBLIC.SONG.ID
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.NAME
     *
     * @return the value of PUBLIC.SONG.NAME
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.NAME
     *
     * @param name the value for PUBLIC.SONG.NAME
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.TEMPO
     *
     * @return the value of PUBLIC.SONG.TEMPO
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    public Integer getTempo() {
        return tempo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.TEMPO
     *
     * @param tempo the value for PUBLIC.SONG.TEMPO
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    public void setTempo(Integer tempo) {
        this.tempo = tempo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.ARTIST_ID
     *
     * @return the value of PUBLIC.SONG.ARTIST_ID
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    public Integer getArtistId() {
        return artistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.ARTIST_ID
     *
     * @param artistId the value for PUBLIC.SONG.ARTIST_ID
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    public void setArtistId(Integer artistId) {
        this.artistId = artistId;
    }
}