package vu.lt.mybatis.dao;

import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.Artist;

import java.util.List;

@Mapper
public interface ArtistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ARTIST
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ARTIST
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    int insert(Artist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ARTIST
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    Artist selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ARTIST
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    List<Artist> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ARTIST
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    int updateByPrimaryKey(Artist record);
}