package vu.lt.mybatis.dao;

import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.Label;

import java.util.List;

@Mapper
public interface LabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LABEL
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LABEL
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    int insert(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LABEL
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    Label selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LABEL
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    List<Label> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LABEL
     *
     * @mbg.generated Wed Apr 08 15:20:28 EEST 2020
     */
    int updateByPrimaryKey(Label record);
}